# Site settings
title: Hanan Basheer
description: Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hanan Basheer
user_description: Hi ğŸ‘‹ <br><br>I'm <b>Hanan Basheer</b>, an <b>Aerospace undergrad</b> âœˆï¸ at <b>IIT Bombay</b>.
                           I'm a <b>Developer</b> & <b>Competitive Programmer</b> ğŸ‘¨ğŸ»â€ğŸ’». I actively code on LeetCode, CodeChef and CodeForces. You can often find me pondering over various unsolved and peculiar problems like <b>Reimann Zeta Function</b>, <b>Game of Life</b>.....
                           ğŸ¤”
                           <p>I love to play <b>Chess â™˜ (Quantam Chess preferably)</b>, e-Games like <b>Valorant</b> & <b>FIFA</b>. Have a timing just below 13 secs on 3x3 <b>Rubik's Cube</b> but can solve Pyraminx, Mirror Cube, Gear Cube, 2x2, 4x4 & 5x5. Also an extreme sports enthusiast, with likes of <b>Football âš½ (Die-Hard Neymar Fan)</b> and <b>Table Tennis</b> ğŸ“....</p>
                           <p>Huge Marvel fan - <b>Iron man</b> ğŸ¤– is my inspiration to come into field of aerospace and coding. RIP ğŸ¥€</p>
                           <p>A passionate <b>cat lover</b> ğŸ˜» (Have a cute kitten, her name's <b>Zeta</b>) and a <b>Palestrato</b> ğŸ’ª (Never miss a leg day !). Sleepy whole day but active at night ğŸ˜ˆ.</p>

user_title: Competitive Programmer
email: dancinglightning2001@gmail.com
instagram_username: __dancing_lightning__
linkedin_username: Hanan Basheer
github_username:  dancinglightning

exclude: ['package.json', 'src' , 'node_modules']
